version: '3.5'

services:
  server:
    container_name: "IggyServer"
    image: "iggyrs/iggy:latest"
    networks:
      - iggy
    ports:
      - "8090:8090"
    volumes:
      - server:/local_data

volumes:
  server:
    driver: local

networks:
  iggy:
    name: iggy-network