[package]
name = "dh"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0.214"
serde_json = { version = "1.0.48", features = ["preserve_order"]}
iggy = "0.6.33"
tokio = "1.41.1"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"